headline: Training courses offered by members of the community.
disclaimer: Trainings listed here are offered by outside companies and the Quarkus project is not responsible for their content.

addtraining: Know of any Quarkus training courses not listed here? <a href="https://github.com/quarkusio/quarkus/discussions/categories/events">Please let us know in the Discussions section</a> so we can share with the community.


courses:

- url: "https://agoncal.teachable.com/courses/category/quarkus"
  affiliation: "Antonio Goncalves"
  descr: "Quarkus courses offered by Antonio Goncalves, a Java Champion, consultant, speaker, and book author on Microservices, Quarkus & Java EE"
  type: "Virtual"
  language: "English"

- url: "https://developers.redhat.com/courses/quarkus"
  affiliation: "Red Hat Developers"
  descr: "Learn Quarkus, a Kubernetes-native Java stack tailored for GraalVM & OpenJDK HotSpot. Stand up an application with a hello endpoint, then get familiar with Hibernate ORM via Panache, a Quarkus component."
  language: "English"
  type: "Virtual"

- url: "https://www.learnquest.com/vendor-training-v20191113-page2.aspx?tp_id=30&categoryid=1314&subcategoryid=5291"
  affiliation: "LearnQuest"
  descr: "Expand your Quarkus knowledge and skills, and become an expert with any of our available courses."
  language: "English"
  type: "Virtual, Classroom"

- url: "https://www.nobleprog.com/quarkus-training"
  affiliation: "NobleProg"
  descr: "Online or onsite, instructor-led live Quarkus training courses demonstrate through interactive hands-on practice how to use Quarkus to build, test, and deploy applications, fully-powered with Java, but with less resource utilization."
  language: "English"
  type: "Virtual, Classroom"

- url: "https://www.udemy.com/topic/quarkus/"
  affiliation: "Udemy"
  descr: "Quarkus related video courses"
  language: "English, Español, Português"
  type: "Virtual"

- url: "https://www.linkedin.com/learning/learning-quarkus"
  affiliation: "Linkedin Learning"
  descr: "Learning Quarkus"
  language: "English"
  type: "Virtual"

- url: "https://www.globalknowledge.com/en-gb/courses/red_hat/cloud_computing/do378"
  affiliation: "Global Knowledge"
  descr: "Develop microservice-based applications with Quarkus and OpenShift."
  language: "English"
  type: "Virtual, Classroom, Company Event"

- url: "https://www.flane.de/en/course/mi-qmpf"
  affiliation: "Fast Lane"
  descr: "Quarkus & MicroProfile Fundamentals (QMPF)"
  language: "English"
  type: "Virtual"

- url: "https://github.com/lunatech-labs/lunatech-beginner-quarkus-course-student-app"
  affiliation: "Lunatech"
  descr: "Lunatech Beginner Quarkus Course Student Repository"
  language: "English"
  type: "Virtual"

- url: "https://www.hco.de/leistungen/quarkus-beratung-coaching-workshop-training"
  affiliation: "Keckler Consulting"
  descr: "Quarkus - Basics We offer you advice, coaching, workshops, training, instruction + advanced training live online and on site!"
  language: "German, English"
  type: "Virtual, Classroom"

- url: "https://www.consol.de/software-engineering/quarkus/"
  affiliation: "Consol Enterprising IT"
  descr: "Quarkus Workshops: From testing to productive deployment"
  language: "German, English"
  type: "Virtual"

- url: "https://openvalue.training/quarkus-essentials/"
  affiliation: "OpenValue Workshops"
  descr: "The essentials of building a Quarkus application from scratch"
  language: "English"
  type: "Classroom, Onsite, Virtual"

- url: "https://www.pluralsight.com/courses/allthetalks-session-86?aid=7010c000002SNsZAAW&promo=&utm_source=non_branded&utm_medium=digital_paid_search_google&utm_campaign=EMEA_FR_Dynamic&utm_content=&cq_cmp=1743999022&gclid=EAIaIQobChMI2Kad4-7a8gIVisx3Ch1CvwUJEAAYASAAEgIx-PD_BwE"
  affiliation: "PluralSight"
  descr: "Cloud-native Java for this Decade with Quarkus"
  language: "English"
  type: "Virtual"

- url: "https://nofluffjuststuff.com/training/174/quarkus_basics"
  affiliation: "Not Fluff Just Stuff"
  descr: "Quarkus is a new microservice framework built by RedHat that competes with Pivotal's Spring Boot."
  language: "English"
  type: "Virtual"

- url: "http://www.encartalabs.com/rh/redhat-microservices-quarkus-training-course.php"
  affiliation: "Encarta Labs"
  descr: "In Red Hat Application Development - Building Microservices with Quarkus training course, you will learn to develop, monitor, test, and deploy microservice-based Java EE applications using Wildfly Swarm and Red Hat OpenShift."
  language: "English"
  type: "Virtual"

- url: "https://www.springest.nl/expandior/quarkus-foundation-training"
  affiliation: "Springest"
  descr: "Quarkus Foundation Training"
  language: "Dutch"
  type: "Virtual"

